spring:
  application:
    name: application

  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    config:
   #   enabled: true
      username: spring_cloud_user
      password: spring_cloud!




