spring:
  application:
    name: configserver
  security:
    user:
      name: spring_cloud_user
      password: spring_cloud!

  cloud:
    config:
      server:
        git:
          uri: https://github.com/ogneyar79/spring-cloud-config-server-repository
   #       clone-on-start: true
          default-label: main
        bootstrap: true
  #        search-paths: twitter_to_kafka
  #    fail-fast: true
server:
  port: 8888
logging:
  level:
    ROOT: INFO
    org.spring.framework.cloud.config: DEBUG


